export const CATEGORY_LABELS: Record<string, string> = {
  bestPicture: "Best Picture",
  leadingActor: "Best Actor",
  leadingActress: "Best Actress",
  directing: "Best Director",
  supportingActor: "Best Supporting Actor",
  supportingActress: "Best Supporting Actress",
  originalScreenplay: "Best Original Screenplay",
  adaptedScreenplay: "Best Adapted Screenplay",
  originalSong: "Best Original Song",
  originalScore: "Best Original Score",
  internationalFeature: "Best International Feature Film",
  animatedFeature: "Best Animated Feature Film",
  documentaryFeature: "Best Documentary Feature",
  productionDesign: "Best Production Design",
  costumeDesign: "Best Costume Design",
  makeup: "Best Makeup and Hairstyling",
  sound: "Best Sound",
  filmEditing: "Best Film Editing",
  cinematography: "Best Cinematography",
  visualEffects: "Best Visual Effects",
  liveActionShort: "Best Live Action Short Film",
  animatedShort: "Best Animated Short Film",
  documentaryShort: "Best Documentary Short Subject",
  casting: "Best Casting",
};

/** Display order for categories (Best Picture first, then major awards, then technical) */
export const CATEGORY_ORDER: string[] = [
  "bestPicture",
  "directing",
  "leadingActor",
  "leadingActress",
  "supportingActor",
  "supportingActress",
  "originalScreenplay",
  "adaptedScreenplay",
  "originalSong",
  "originalScore",
  "internationalFeature",
  "animatedFeature",
  "documentaryFeature",
  "productionDesign",
  "costumeDesign",
  "makeup",
  "sound",
  "filmEditing",
  "cinematography",
  "visualEffects",
  "liveActionShort",
  "animatedShort",
  "documentaryShort",
  "casting",
];

/** Categories where the winner is identified by nameSlug (person) rather than movieSlug */
export const NAME_SLUG_CATEGORIES: string[] = [
  "directing",
  "supportingActor",
  "supportingActress",
  "leadingActress",
  "leadingActor",
  "originalSong",
  "casting",
];
